version: '3.8'

services:
  vaccination-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - VACCINATION_DATA_SOURCE=csv
      - VACCINATION_DATA_PATH=vaccination_data.csv
    volumes:
      - ./data:/app/data
      - ./vaccination_data.csv:/app/vaccination_data.csv
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: vaccination-dashboard-network